### ISSUE TITLE
Horizontal offset stuck at 27

### ISSUE THREAD

**Issue by stefanofabbriiv** [medhachaitanya/Pure-Battery-Analytics#3] opened 2021-03-29 16:58 UTC
Hi I cannot edit horizontal offset, that is 0 by default. When I try to modify it (with any value), it immediately sets to 27 (?) and stuck. Colors and other two values works correctly. 
Let me know... Thanks :) 

![image](https://user-images.githubusercontent.com/72146861/112872225-69ea1080-90c0-11eb-8849-a89f787eaa6c.png)

**Comment by stefanofabbriiv** [comment] 2021-03-29 19:22
Ok I directly edited settings.dat and now it's ok. 
You should not give up this app :)

**Comment by medhachaitanya** [comment] 2021-03-31 04:39
Thank you. I could not replicate this issue. As its already solved, I'm closing this issue.

**Closed as completed by medhachaitanya** 2021-03-31 04:39 UTC

**Comment by medhachaitanya** [comment] 2021-04-16 22:29
@stefanofabbriiv Just gave an update to the app. It's fixed now. I was testing on the dev version of the app and not on the store version which is why I was not able to replicate. Thank you so much for sharing the bug.

**Comment by stefanofabbriiv** [comment] 2021-04-17 07:32
Ok thank you so much! So happy for this. @medhachaitanya 
Have a good weekend 👍🏻

**Comment by stefanofabbriiv** [comment] 2021-04-20 08:04
@medhachaitanya Hi, I got MS Store update for add-on, now hor-offset is working. :) 
I'm noticing that now I can open the app multiple times, is this an intentional feature? No much trouble btw 
(green 95s in screen)
![image](https://user-images.githubusercontent.com/72146861/115360211-b73d3780-a1bf-11eb-8bce-30fc202200ba.png)

**Comment by medhachaitanya** [comment] 2021-04-20 16:07
@stefanofabbriiv Thanks for confirming. I am aware of it. It's not intentional but it's certainly not a bug. It's because of the way the app has been ported from Win32 to UWP. I'll see if I can do something about it. 

But to be honest, I ignored it because people launch the app only if they don't see the icon :D. If they happen to see multiple icons they usually exit the ones they don't need. I appreciate your efforts in helping me to keep the app bug-free. Thanks again @stefanofabbriiv.
